---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Insis api"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
- "https"
paths:
  /agenda:
    post:
      tags:
      - "agenda"
      summary: "Get week schedule agenda"
      description: ""
      operationId: "get_schedule_agenda"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/AgendaEvent"
        404:
          description: "No events found"
      x-swagger-router-controller: "insis_api.controllers.agenda_controller"
  /subject/enrolled:
    post:
      tags:
      - "subject"
      summary: "Get enrolled subjects"
      description: ""
      operationId: "get_enrolled_subjects"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Subject"
        404:
          description: "No subjects found"
      x-swagger-router-controller: "insis_api.controllers.subject_controller"
  /grades/{subjectId}:
    post:
      tags:
      - "grades"
      summary: "Get grades from subject"
      description: ""
      operationId: "get_grades_from_subject"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "subjectId"
        in: "path"
        description: "ID of subject which grades needs to be fetched"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Exam"
        404:
          description: "No grades found"
      x-swagger-router-controller: "insis_api.controllers.grades_controller"
  /exam:
    post:
      tags:
      - "exam"
      summary: "Get all exams"
      description: ""
      operationId: "get_exam"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Exam"
        404:
          description: "No exams found"
      x-swagger-router-controller: "insis_api.controllers.exam_controller"
  /exam/{exam_id}:
    post:
      tags:
      - "exam"
      summary: "Get exam by id"
      description: ""
      operationId: "get_exam_by_id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "exam_id"
        in: "path"
        description: "ID of exam that needs to be fetched"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Exam"
        404:
          description: "Exam not found"
      x-swagger-router-controller: "insis_api.controllers.exam_controller"
  /exam/{exam_id}/enroll:
    post:
      tags:
      - "exam"
      summary: "Enroll exam with id"
      description: ""
      operationId: "enroll_exam_by_id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "exam_id"
        in: "path"
        description: "ID of exam to enroll"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Unsuccessful operation"
        404:
          description: "Exam not found"
      x-swagger-router-controller: "insis_api.controllers.exam_controller"
  /exam/{exam_id}/disenroll:
    post:
      tags:
      - "exam"
      summary: "Disenroll exam with id"
      description: ""
      operationId: "disenroll_exam_by_id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "exam_id"
        in: "path"
        description: "ID of exam to disenroll"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Unsuccessful operation"
        404:
          description: "Exam not found"
      x-swagger-router-controller: "insis_api.controllers.exam_controller"
  /exam/enrolled:
    post:
      tags:
      - "exam"
      summary: "Get enrolled exams"
      description: ""
      operationId: "get_enrolled_exam"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Insis user credentials"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Exam"
        404:
          description: "No exams found"
      x-swagger-router-controller: "insis_api.controllers.exam_controller"
definitions:
  User:
    type: "object"
    required:
    - "password"
    - "username"
    properties:
      username:
        type: "string"
      password:
        type: "string"
    example:
      password: "password"
      username: "username"
  Exam:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      accessibility:
        type: "string"
      ident:
        type: "string"
      subject:
        type: "string"
      department:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      room:
        type: "string"
      type:
        type: "string"
      teacher:
        type: "string"
      availability:
        type: "string"
      sign_in_from:
        type: "string"
        format: "date-time"
      sign_in_to:
        type: "string"
        format: "date-time"
      sign_out_to:
        type: "string"
        format: "date-time"
    example:
      date: "2000-01-23T04:56:07.000+00:00"
      teacher: "teacher"
      ident: "ident"
      subject: "subject"
      sign_out_to: "2000-01-23T04:56:07.000+00:00"
      id: 0
      availability: "availability"
      department: "department"
      type: "type"
      room: "room"
      sign_in_from: "2000-01-23T04:56:07.000+00:00"
      sign_in_to: "2000-01-23T04:56:07.000+00:00"
  AgendaEvent:
    type: "object"
    properties:
      day:
        type: "string"
      time_from:
        type: "string"
        format: "time"
      time_to:
        type: "string"
        format: "time"
      subject:
        type: "string"
      type:
        type: "string"
      room:
        type: "string"
      capacity:
        type: "integer"
        format: "int64"
    example:
      time_to: "time_to"
      time_from: "time_from"
      subject: "subject"
      type: "type"
      day: "day"
      room: "room"
      capacity: 0
  Subject:
    type: "object"
    properties:
      ident:
        type: "string"
      name:
        type: "string"
      department:
        type: "string"
      obligation:
        type: "string"
      exam_type:
        type: "string"
      credits:
        type: "integer"
        format: "int64"
      lang:
        type: "string"
      subject_group:
        type: "string"
      agenda:
        type: "string"
    example:
      exam_type: "exam_type"
      credits: 0
      ident: "ident"
      obligation: "obligation"
      name: "name"
      subject_group: "subject_group"
      department: "department"
      lang: "lang"
      agenda: "agenda"
